services:
  schematic_web:
    image: docker.io/intellectualsites/schematic-web:latest
    container_name: schematic_web
    restart: unless-stopped
    ports:
      - 3001:80
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web/config.json:/usr/share/nginx/html/config.json
    depends_on:
      - arkitektonika
  arkitektonika:
    image: docker.io/intellectualsites/arkitektonika:latest
    container_name: Arkitektonika
    restart: unless-stopped
    ports:
      -  3000:3000
    volumes:
      - ./data:/app/app/data
    environment:
      - LOG_LEVEL=DEBUG